name: Build and Push to GHCR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x' 
          dotnet-quality: 'preview'

      - name: Run Unit Tests & Collect Coverage
        run: dotnet test QuestorTeste/QuestorTeste.UnitTests/QuestorTeste.UnitTests.csproj --configuration Release --settings QuestorTeste/coverage.runsettings --collect:"XPlat Code Coverage"

      - name: Report Code Coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: QuestorTeste/QuestorTeste.UnitTests/TestResults/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
          
      - name: Download SVG Badge
        if: github.event_name != 'pull_request'
        run: |
          BADGE_URL=$(grep -o 'https://img.shields.io/badge/[^)]*' code-coverage-results.md)
          curl -s "$BADGE_URL" -o coverage.svg
          
      - name: Commit Code Coverage Badge
        uses: stefanzweifel/git-auto-commit-action@v5
        if: github.event_name != 'pull_request'
        with:
          commit_message: "chore: atualiza badge de code coverage [skip ci]"
          file_pattern: coverage.svg

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: . 
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:devel